app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(shipname_dd = "POLA MUROM")
app$setInputs(shiptype_dd = "High Special")
app$setInputs(shipname_dd = "VALO")
app$setInputs(shiptype_dd = "Passenger")
app$setInputs(shiptype_dd = "Tanker")
app$setInputs(shipname_dd = "BESIKTAS ICELAND")
app$setInputs(shipname_dd = "AMUR STAR")
app$setInputs(shipname_dd = "TRANS FJELL")
app$setInputs(shipname_dd = "PATANI")
app$setInputs(shipname_dd = "LUKE")
app$setInputs(shiptype_dd = "Tug")
app$setInputs(shiptype_dd = "Unspecified")
app$setInputs(shipname_dd = "VTS GAOTEBORG")
app$setInputs(shipname_dd = "VTS BALTIYSK")
app$setInputs(shipname_dd = "VTS 2734488")
app$setInputs(shiptype_dd = "Tug")
app$setInputs(shipname_dd = "AURA")
app$setInputs(shiptype_dd = "Tanker")
app$setInputs(shipname_dd = "NORDEN")
app$setInputs(shipname_dd = "WISBY WAVE")
app$setInputs(shipname_dd = "AURA")
app$setInputs(shipname_dd = "ABIGAIL")
app$setInputs(shipname_dd = "ANGARA")
app$setInputs(shipname_dd = "VALERIY ZELENKO")
app$setInputs(shiptype_dd = "Tug")
app$setInputs(shipname_dd = "SAR 111261105")
app$setInputs(shiptype_dd = "Tanker")
app$setInputs(shipname_dd = "FURE FLADEN")
app$snapshot()
