app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(shiptype_dd = "Fishing")
app$setInputs(shipname_dd = "CHRISTINA MICHELLE")
app$snapshot()
app$setInputs(shipname_dd = "R 355 TRINE LOUISE")
app$setInputs(shiptype_dd = "Navigation")
app$setInputs(shiptype_dd = "Tug")
app$setInputs(shipname_dd = "AURA")
app$setInputs(shipname_dd = "SAR 111265121")
